# Generated by Django 3.0.5 on 2020-07-05 20:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Başlık')),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ad')),
                ('surname', models.CharField(max_length=50, verbose_name='Soyad ')),
                ('salary', models.FloatField(verbose_name='Maaş')),
                ('birthdate', models.DateField(verbose_name='Doğum Tarihi ')),
                ('cityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personel.Cities', verbose_name='Yazar Adı')),
            ],
        ),
    ]
