 
print(1 < 2 and "Şamil" == "Şamil")
print(2 > 3 and "Şamil" == "Şamil")
print(2 == 2 and 3.14 < 1.98 and "Elma" != "Armut")
print("**********************************")
print(1 < 2 or "Şamil" == "Şamil")
print(2 > 3 or "Şamil" == "Şamil")
print(2 == 2 or 3.14 < 1.98 or "Elma" != "Armut") 
print("**********************************")
print(  "Şamil" == "Kamil")
print( not  "Şamil" == "Kamil")
print("**********************************")
print(not (1.25 > 3.85 or ( 2 != 2 and "Murat" == "Murat")))
